version: "3.8"

services:
  #########################################################################
  # 1) Servidor NFS (simulando EFS)
  #########################################################################
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      # Mapeia a pasta local ./nfs-data para /data dentro do container,
      # que será exportada via NFS
      - ./nfs-data:/data
    ports:
      # Expondo porta 2049 (NFS) no host, para permitir montagens
      - "2049:2049"

  #########################################################################
  # 2) LocalStack (versão community) - caso você precise
  #########################################################################
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - DEBUG=1
      - SERVICES=s3,cloudformation,lambda,iam   # Exemplos de serviços
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"

  #########################################################################
  # 3) Container "backup-runner"
  #    - Instala nfs-common (para montar NFS)
  #    - Monta o NFS exportado pelo nfs-server
  #    - Executa o script my_script.sh
  #########################################################################
  backup-runner:
    image: ubuntu:22.04
    container_name: backup-runner
    depends_on:
      - nfs-server
    volumes:
      # Monta o script local "my_script.sh" dentro do container
      - ./my_script.sh:/usr/local/bin/manage_backups.sh:ro
    entrypoint: >
      bash -c "
        apt-get update &&
        apt-get install -y nfs-common &&
        mkdir -p /mnt/efs-simulada &&
        # Monta o NFS vindo do serviço 'nfs-server'
        mount -t nfs -o nfsvers=4 nfs-server:/data /mnt/efs-simulada &&
        # Executa o script
        chmod +x /usr/local/bin/manage_backups.sh &&
        /usr/local/bin/manage_backups.sh
      "

